### ISSUE TITLE
Release Checklist for 1.118.0

### ISSUE THREAD

**Issue by DeeDeeG** [pulsar-edit/pulsar#1027]
# Regular Release 1.118.0

- [x] ChangeLog updated (`CHANGELOG.md` and `welcome` package):
  - https://github.com/pulsar-edit/pulsar/pull/1025
- [x] Blurb Text Complete (Comment Below)
- [x] Version Bump PR Created
  - https://github.com/pulsar-edit/pulsar/pull/1026
- [x] Binaries Uploaded to GitHub (Including renamed binaries, and SHASUM file)
- [x] Release Posted! 🎊
- [x] Update Chocolatey Release
- [x] Website Links updated
- [x] Blog Post
- [x] Discord Announcement
- [x] Reddit Announcement
- [x] Mastodon Announcement
- [x] Lemmy Announcement

### What benefits does this feature provide?

A new Regular release of Pulsar for all to enjoy!

### Any alternatives?

There is no stopping the release train!

**Comment by confused-Techie** [comment]
Blurb possibility:

```md
# Hot dog, it's another Pulsar release!

Pulsar v1.118.0 brings lots of love to syntax highlighting, while still containing the usual set of features and fixes.

Along with various other Tree-sitter fixes and improvements we have improved documentation about Tree-sitter's usage, an updated PHP parser, fixed syntax quoting on Clojure, as well as Clojure highlighting support for metadata and "def" elements, as well as improved injection points for Clojure.

Within the Pulsar application the new setting `core.allowWindowTransparency` lets users set the background of the editor to support transparency, although it still must be utilized by a community theme to actually be transparent. The `textChanged` property is now accurate when characters are deleted, and EDN files are back to being detected as Clojure, but will highlight correctly as EDN.

The Tree-sitter syntax highlighting system now has a new test for queries `ancestorTypeNearerThan` which helps matching the *first* type as an ancestor, as well as supporting a second `buffer` argument in the `content` field of `addInjectionPoint` for easier customization.

Finally for our community package's developers, they will be glad to hear that first time publication issues have been resolved with a rewrite of the `ppm publish` command, improving the workflow, and ensuring things work properly with the updated backend.

As always thanks a ton to all of our users and supports for sticking with the Pulsar project, and until next time, happy coding, and see you amongst the stars!

- The Pulsar Team
```

**Comment by DeeDeeG** [comment]
A round two/second pass of the blurb?

```
# Hot dog, it's another Pulsar release!

Get your grills ready, Pulsar v1.118.0 is cooking with gas! This release brings lots of love to syntax highlighting, along with a zesty sprinkling of features and fixes.

We've got Tree-sitter fixes and improvements, including improved documentation around Tree-sitter's usage, an updated PHP parser, fixed syntax quoting on Clojure, as well as enhanced Clojure highlighting support for metadata and "def" elements, as well as improved injection points for Clojure. EDN files are back to being detected as Clojure, but will highlight correctly as EDN. Tasty!

Within the Pulsar application the new setting `core.allowWindowTransparency` lets users set the background of the editor to support transparency, although transparent CSS styles must be set by a theme or user stylesheet for Pulsar to actually be transparent. The `textChanged` property is now accurate when characters are deleted.

The Tree-sitter syntax highlighting system now has a new test for queries `ancestorTypeNearerThan` which helps matching the *first* type as an ancestor, as well as supporting a second `buffer` argument in the `content` field of `addInjectionPoint` for easier customization.

Finally, for our community package developers, they will be glad to hear that first time publication issues have been resolved with a rewrite of the `ppm publish` command, improving the workflow, and ensuring things work properly with the updated backend. Please feel free to share what you've been cooking by publishing your packages!

As always, thanks a ton to all of our users and supporters for sticking with the Pulsar project, and until next time, happy coding, and see you amongst the stars!

- The Pulsar Team
```

**Comment by Daeraxa** [comment]
[Annoying Alien](https://www.reddit.com/r/pulsaredit/comments/1dhwh2m/hot_dog_its_another_pulsar_release_pulsar_11180/?)  
[Luscious Lemming](https://lemmy.ml/post/16977633)
[Magnificent Mammoth]() - See teams chat

**Comment by Daeraxa** [comment]
Above all done now

**Comment by confused-Techie** [comment]
@Daeraxa Thanks a ton for getting those last steps in there, appreciate it!
