### ISSUE TITLE
Pulsar v1.119.0 Release Checklist

### ISSUE THREAD

**Issue by confused-Techie** [pulsar-edit/pulsar#1055]
### Have you checked for existing feature requests?

- [X] Completed

### Summary

# Regular Release

- [x] ChangeLog updated (`CHANGELOG.md` and `welcome` package)
- [x] Blurb Text Complete (Comment Below)
- [x] Version Bump PR Created
- [x] Binaries Uploaded to GitHub (Including renamed binaries, and SHASUM file)
- [x] Release Posted! 🎊
- [x] Update Chocolatey Release
- [x] Website Links updated
- [x] Blog Post
- [x] Discord Announcement
- [x] Reddit Announcement
- [x] Mastodon Announcement
- [x] Lemmy Announcement

### What benefits does this feature provide?

n/a

### Any alternatives?

n/a

**Comment by DeeDeeG** [comment]
Blurb primarily by `@confused-Techie`, with copy-editing suggestions from `@Daeraxa` and with the benefit of additional clarification from `@savetheclocktower` on a technical point when asked about it. Which I used to touch up the "For macOS" sentence.

```
# Pulsar v1.119.0 is live!

While a smaller release this time around, v1.119.0 still manages to pack a punch.

For macOS, we've gone to great lengths to ensure Pulsar should build just fine on macOS 13+, while our Linux users get greater compatibility for DevTools on various platforms. For our programmers, there's been more of the constant incremental improvements to various languages' built-in syntax highlighting and code folding this time around, with a focus on PHP, Python, Javascript, Typescript, Shell script, and C.

As always thanks a ton to all of those that support the project and keep it moving forward, we appreciate you all, and look forward to seeing you amongst the stars.

\- The Pulsar Team
```

**Comment by Daeraxa** [comment]
Xenomorph - https://www.reddit.com/r/pulsaredit/comments/1e6tlww/pulsar_v11190_is_live/?
Proboscidea - https://fosstodon.org/@pulsaredit
Arvicolinae - https://lemmy.ml/post/18150318

**Comment by confused-Techie** [comment]
And I've just done the Discord announcement, thanks for all the teamwork on this one!
