### ISSUE TITLE
command line atom commands not working in pulsar 1.63.2022120404

### ISSUE THREAD

**Issue by ljsinclair** [pulsar-edit/pulsar#194]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Does your issue already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

Installed Pulsar edit Pulsar 1.63.2022120404 from binaries.
`atom` commands fail with errors:
* `atom --safe`
* `atom --version`

FYI, I also tried `pulsar` in place of `atom` in case that worked but got the same errors.

This could mean it's genuinely broken, or there are changed commands for Pulsar.

Source of debugging info from bug checklist above:
* https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging
* https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html

### Which OS does this happen on?

🪟 Windows

### OS details

Windows 10 Pro 22H2 19045.2251

### Which CPU architecture are you running this on?

64-bit(x86_64)

## Part 1 - install pulsar

1. Download Windows binary.zip from Cirrus CI site > https://cirrus-ci.com/task/4754549466988544
2. Extract files from zip
3. Install software using Pulsar Setup 1.63.2022120404.exe

Application auto-starts on install completion.

## Part 2 - attempt to open in safe mode

(Issue checklist links to: https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)

Open windows command line and enter the command `atom --safe`

## Result

Error message:

Windows CMD:
```
C:\Users\me>atom --safe
'atom' is not recognized as an internal or external command,
operable program or batch file.
```

Windows Powershell:

```
PS C:\Users\me> atom --safe
atom : The term 'atom' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ atom --safe
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (atom:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

Git bash:

```
$ atom --safe
bash: atom: command not found

```

**Comment by confused-Techie** [comment]
On this, we no longer use `atom` for our CLI. This is intended behavior.

Although you should now be able to use `pulsar` for these activities. With for the most part the same commands and flags.

The only known issue, is that some systems will not install the path to Pulsar natively during the install process, which we are working on, but for the time being you may have to install it.

Since you are on Windows I'll point out the above issue will effect you. If you were to install the Pulsar Binary and add it to your system path, you'd be able to run `pulsar --safe` to open in safe mode.

But as I now right this up, I realize that this may not be fully explained in our docs. So will leave this open until we can revamp or create a section from scratch for this

**Comment by ljsinclair** [comment]
I suspected you wouldn't be using `atom` anymore, which means those 2x docs pages need to be updated :)

**Comment by confused-Techie** [comment]
Yes they do, although quick note, those links to documentation are the `Atom archive` they are docs taken from Atom that we won't be updating or modifying the content of. They are in place for where our documentation lacks or is not complete, to try and give as much info as possible. Although in their place we do currently have an issue open to create the respective same docs but for Pulsar. Or at least for part of the CLI usage, but we will have to review adding a doc page for the CLI commands altogether

**Comment by Daeraxa** [comment]
There is a PR to add documentation on how to use the replacement apm command which is `pulsar -p` but you are correct in that the entire `hacking-pulsar` section needs to be created still which is on my list of things to do pretty urgently which would involve standard `pulsar` command usage.

The commands work fine on Linux from a .deb install (and would work for .rpm and on macOS) as an example but due to differences in the Atom and Pulsar installers it doesn't work on Windows currently. You can also see this issue I raised about this from a global perspective - https://github.com/pulsar-edit/pulsar/issues/187

**Comment by ljsinclair** [comment]
Ok, so apologies, I didn't mentally link #187 with the problem I was experiencing >.< My bad.

**Comment by confused-Techie** [comment]
> Ok, so apologies, I didn't mentally link #187 with the problem I was experiencing >.< My bad.

You're all good, this does point out something else that does need to be done, so thanks for that 😄

**Comment by Daeraxa** [comment]
It isn't *quite* the same, #187 is more of an idea to enhance the app in general where this issue is a specific and real problem.

**Comment by ljsinclair** [comment]
Safe mode and other commands now work in 1.63.20221206.
I'd update the documentation myself but I can't find it >.<
Is there a separate doco repo? Because I'd suggest as a long-term strategy that would be better than smooshing into the main site :)

**Comment by confused-Techie** [comment]
> Safe mode and other commands now work in 1.63.20221206. I'd update the documentation myself but I can't find it >.< Is there a separate doco repo? Because I'd suggest as a long-term strategy that would be better than smooshing into the main site :)

Amazing to hear the CLI is now working on Windows. But currently all of our Documentation is hosted on [`pulsar-edit.github.io`](https://github.com/pulsar-edit/pulsar-edit.github.io). And the markdown here builds our website. 

This really seems to be the same as what Atom did, and as far as I'm aware is our plans for our documentation. Are you suggesting a special repo for docs for ease of readability?

**Comment by ljsinclair** [comment]
07 are the last 2 numbers @confused-Techie :)

**Comment by ljsinclair** [comment]
Oh, and re: separate repo
As far as editing and maintaining docs, it's **always** easier if they're in a standalone repo that'll only ever have doc updates on it. Mixing the site and docs means there's a higher chance of merge conflicts.
For usability purposes, it's good to have a single site to find all the docs, separate to the main site, and usually on a subdomain (e.g., docs.pulsar.com)
This means the user can find all the docs in one place, and you can setup a single button/link on the main site so they can be accessed.

**Comment by confused-Techie** [comment]
Thanks @ljsinclair but super interesting this fixed it. For reference to everyone else, [here](https://cirrus-ci.com/task/5919248162226176) is the build that has seemingly resolved this issue. But the strange thing, that is from a WIP Branch I have where I'm troubleshooting the `dugite` errors we are seeing elsewhere. To my knowledge this shouldn't have affected how Windows commands run, or especially adding Pulsar to the System Path. Since from that commit I believe the only change I made was to how `node_modules` are included into the Asar Archive, as well as attempting (and failing) to unpack `dugite`s bundled git. So super strange this fixed it, but I'll test myself to see if I can reproduce it, since if those changes fixed this issue, then that's awesome, although unexplained

**Comment by Daeraxa** [comment]
> Oh, and re: separate repo As far as editing and maintaining docs, it's **always** easier if they're in a standalone repo that'll only ever have doc updates on it. Mixing the site and docs means there's a higher chance of merge conflicts. For usability purposes, it's good to have a single site to find all the docs, separate to the main site, and usually on a subdomain (e.g., docs.pulsar.com) This means the user can find all the docs in one place, and you can setup a single button/link on the main site so they can be accessed.

They are. Well almost. All the actual Pulsar editor docs are all on the repo @confused-Techie linked. The main website is just for docs and blogs, the only subdomains on it are used for the package frontend. There are some exceptions where the docs can still be *found* on the main website but the original documents are on other repos, this is for non-editor stuff like the package backend and org docs. There shouldn't ever be a risk of merge conflicts because there is no duplication of the content.

**Comment by marnen** [comment]
@ljsinclair:
> As far as editing and maintaining docs, it's **always** easier if they're in a standalone repo that'll only ever have doc updates on it.

Perhaps I shouldn’t say much since I haven’t started contributing to Pulsar yet, but…I’d strongly dispute this as a general principle. For many projects, it makes a lot of sense to have the documentation in the same repo as the code, so that the same pull request can update both the code and the documentation for it. 

> Mixing the site and docs means there's a higher chance of merge conflicts.

Not in my experience. Why would this be so?

> For usability purposes, it's good to have a single site to find all the docs, separate to the main site, and usually on a subdomain (e.g., docs.pulsar.com)

Sure, but that’s a separate issue from the repo structure.

**Comment by ljsinclair** [comment]
Hi @marnen - 

>...but…I’d strongly dispute this as a general principle. For many projects, it makes a lot of sense to have the documentation in the same repo as the code, so that the same pull request can update both the code and the documentation for it.

Oh, wouldn't that be a lovely world. In my experience (20+ years tech writing), there's zero integration between issue/fix tickets and docs, and documenters tend to trip over new functionality rather than being informed through tickets.

Re: Merge conflicts
I'm working with an org right now and there are merge conflicts all over the place, and it gets so bad sometimes that in order to merge in changes I have to copy changes to a newly created branch off main and then merge/deploy from there. Someone said something about it being because there's a "rebase" policy in play, but it's **super** annoying and very cumbersome. This is a reason to keep knowledge-based documentation separate from general updates to a site.

Re: single site/single repo
By this I mean there's a "docs" repo that is deployed to a "docs" subdomain (or something similar). This makes it easier for users to find the docs and they remain focused on **just** documentation rather than a mix of sales/marketing, blogging AND knowledge-based docs.

**Comment by ljsinclair** [comment]
> Thanks @ljsinclair but super interesting this fixed it. For reference to everyone else, [here](https://cirrus-ci.com/task/5919248162226176) is the build that has seemingly resolved this issue. But the strange thing, that is from a WIP Branch I have where I'm troubleshooting the `dugite` errors we are seeing elsewhere. To my knowledge this shouldn't have affected how Windows commands run, or especially adding Pulsar to the System Path. Since from that commit I believe the only change I made was to how `node_modules` are included into the Asar Archive, as well as attempting (and failing) to unpack `dugite`s bundled git. So super strange this fixed it, but I'll test myself to see if I can reproduce it, since if those changes fixed this issue, then that's awesome, although unexplained

Did I mention I'm also experienced in testing software. Back in the old days I used to be able to get a screen to fill with Access Violations before the machine ran out of memory and crashed hard. Those were the days ;)

**Comment by marnen** [comment]
This is probably off topic and I don’t want to clutter up this thread, but I can’t resist responding to a couple of @ljsinclair’s points. 

> In my experience (20+ years tech writing), there's zero integration between issue/fix tickets and docs, and documenters tend to trip over new functionality rather than being informed through tickets.

Wow, from the development side that sounds like the exact kind of workflow I try *not* to have. I’m sorry my colleagues have failed you this badly. 

> 
> Re: Merge conflicts I'm working with an org right now and there are merge conflicts all over the place, and it gets so bad sometimes that in order to merge in changes I have to copy changes to a newly created branch off main and then merge/deploy from there. 

That should never ever be necessary. 

> Someone said something about it being because there's a "rebase" policy in play, 

Entirely possible. Rebase workflows tend to make Git *very* hard to use well. 

> This is a reason to keep knowledge-based documentation separate from general updates to a site.

No, it’s a reason not to use a rebase workflow. What you’re describing generally wouldn’t happen with a merge workflow even if docs are in the same repo with everything else. 

> 
> Re: single site/single repo By this I mean there's a "docs" repo that is deployed to a "docs" subdomain (or something similar). This makes it easier for users to find the docs and they remain focused on **just** documentation rather than a mix of sales/marketing, blogging AND knowledge-based docs.

I think you’re conflating site structure and repo structure. They don’t have to be the same, and often aren’t.

**Comment by ljsinclair** [comment]
Hi @marnen 

>Wow, from the development side that sounds like the exact kind of workflow I try not to have

Oh that would be lovely. To be included... I can dream I suppose? ;)

> That should never ever be necessary.

I'm right there with you. It's really stressful.

> Entirely possible. Rebase workflows tend to make Git very hard to use well.
> No, it’s a reason not to use a rebase workflow. 

I totally agree there! It feels a little like trying to pull together changes on MS Word docs, needing to remember copy A was given to Fred, copy B was given to the PHB who hasn't given it back, etc. 

> I think you’re conflating site structure and repo structure

Separating help from site content may also be conceptualised in terms of:
* Site content tends to be marketing-centric and talking about the benefits of the application, and ultimately selling it to the end user. It'll also tend to be informal English
* Help content is factual and written in a completely different way, it's more formalised and direct English because it's telling a user what to do and how to do it. The assumption here is they've already been sold at and just want to get in and do things.

(apologies to those who speak other languages) :D

Hopefully that helps :D

**Comment by confused-Techie** [comment]
Alright, so it seems like the original reason this was created has been resolved. As it's a non-issue and a change we had made that needed some docs updated which are now done.

So I'll go ahead and close this one, and for any ongoing issues being discussed above, if needed, can be moved to be their own issue. Thanks for all the communication on this one!
