### ISSUE TITLE
Tests to Fix

### ISSUE THREAD

**Issue by confused-Techie** [pulsar-edit/pulsar#511]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

Over time in efforts to achieve green CI we have opted to comment out difficult to resolve tests. But now overtime the issues we created to mark those have built up, so to avoid unnecessary bloat to our issue board I'll go ahead and combine them here.

Any other maintainers of Pulsar should have no issue adding new ones to this board if needed, or hopefully checking the checkbox to indicate that the test is no longer commented out. But with that said:

* [ ] Dock tests: `spec/workspace-element-spec.js` - Previously issue #30 - [Commit Commenting out](https://github.com/pulsar-edit/pulsar/commit/70a09de373d4f406f2f3a1e3cfccdd12b61f0e2a)
* [ ] Editor Update tests: `spec/update-manager-spec.js` - Previously issue #49 
* [ ] Flaky test: `N/A` - Previously issue #129 
* [ ] Command Installer tests: `spec/command-installer-spec.js` - Previously issue #303 
* [ ] `tree-view` Specs commented out. [Commit Commenting out](https://github.com/pulsar-edit/pulsar/pull/513/commits/5a166ef3761c688dca2d1d3ac702a42553a7cd6b)

### Pulsar version

N/A

### Which OS does this happen on?

❓ Other(Please specify in the OS details field below)

### OS details

N/A

### Which CPU architecture are you running this on?

None

### What steps are needed to reproduce this?

N/A

### Additional Information:

N/A

**Comment by mauricioszabo** [comment]
Glad to say that this was done a while ago :)

**Comment by mauricioszabo** [comment]
Wait, maybe not - I think I misread the description
