### ISSUE TITLE
v1.107.0 Release Checklist

### ISSUE THREAD

**Issue by confused-Techie** [pulsar-edit/pulsar#635]
### Have you checked for existing feature requests?

- [X] Completed

### Summary

# Regular Release

- [x] ChangeLog updated (`CHANGELOG.md` and `welcome` package)
- [x] Blurb Text Complete (Comment Below)
- [x] Version Bump PR Created
- [x] Binaries Uploaded to GitHub (Including renamed binaries, and SHASUM file)
- [x] Release Posted! 🎊
- [x] Website Links updated
- [x] Blog Post
- [x] Discord Announcement
- [x] Reddit Announcement
- [x] Mastodon Announcement

### What benefits does this feature provide?

N/A

### Any alternatives?

N/A

### Other examples:

This issue is using the template from [`.github#199`](https://github.com/pulsar-edit/.github/pull/199). The PR is unmerged, but full release details and guide can be found there.

Any discussion as for drafting this release can occur on this issue if preferred.

**Comment by confused-Techie** [comment]
The ChangeLog has been updated in #636

**Comment by confused-Techie** [comment]
Changelog has been merged

**Comment by confused-Techie** [comment]
Version Bump PR Available here: https://github.com/pulsar-edit/pulsar/pull/637

**Comment by Daeraxa** [comment]
Draft release blurb - comments welcome. I'm really starting to struggle with these titles lol.

---

# Fresh off the CI press: Pulsar 1.107.0 is available now!

Another month and another Pulsar release! This month is features a bunch of those all important quality of life updates. We have a whole host of bugfixes and upgrades for you along with a sprinkling of new features.

To kick things off we have now resolved an issue which has been hanging around since we began this project. As we no longer had the same method of installing the software as Atom, we created an issue for Windows users where the `pulsar` and `ppm` were not being added to PATH. The upshot of this was some rather important Pulsar features were no longer working by default on Windows - namely the ability to launch pulsar by just running `pulsar` in run or cmd/powershell (you can find more in our [launch manual](https://pulsar-edit.dev/docs/launch-manual/sections/getting-started/#opening-modifying-and-saving-files) on how you can use this to open Pulsar directly to a particular file, line and even column). You can also run `pulsar --help` to display all the available options.

Please note that whilst we have this working now for the most part, the `-p`/`--package` option as well as `ppm` still needs some more development work. However until this has been completed you can still access Pulsar package management from the command line on Windows by simply using `apm` (what `ppm` is still named underneath) in place of those commands.

Next we have an update to our `less-cache` package which bumps the version of [less](https://lesscss.org/) used by Pulsar from `3.12.2` to `4.1.3` which adds some new functionality but also introduces a breaking change regarding using division in math expressions. You can read more about this in our recent [community update blog post](https://pulsar-edit.dev/blog/20230701-Daeraxa-JulyUpdate.html#less-cache-package-update) on this subject.

To continue the trend of new developments with the modern [Tree-sitter implementation](https://pulsar-edit.dev/blog/20230601-Daeraxa-JuneUpdate.html#tree-sitter-updates-are-live), we now have a new grammar for `TOML` files as well as a couple of fixes to some issues that have been discovered with the new implementation.

Another nice feature recently added is a new API endpoint - `atom.versionSatisfies()`. No longer do package maintainers (or any other Pulsar hacker) need to write their own way of checking for Pulsar versions, we now have an inbuilt way of doing it which will hopefully alleviate some of the problems we have seen with some packages using, lets just say "less than ideal" methods of version checking. You can read more about it on the [PR](https://github.com/pulsar-edit/pulsar/pull/588).

And lastly, in case you missed it from the community update, we have resolved an issue due to a downstream dependency that was causing Pulsar to get falsely flagged by virus checkers. You can read more about this from the [update post](https://pulsar-edit.dev/blog/20230701-Daeraxa-JulyUpdate.html#antivirus-es5-ext-issue).

And that brings us to a close for the `1.107.0` release notes. As ever a huge thank you to our wonderful donors and community members who not only make this project possible but worthwhile.

Until next time, happy coding and see you amongst the stars!

  - The Pulsar Team

**Comment by confused-Techie** [comment]
Notes: @Daeraxa 
 
* "This month is features a bunch" => "This month features a bunch"
* Also an aside to the breaking changes of `less-cache` it might be worth it to mention that Pulsar will try to automatically fix these issues during load

**Comment by savetheclocktower** [comment]
* `s/quality of life/quality-of-life/` (adjectival means hyphens)
* `some packages using, lets just say "less than ideal" methods` should be `some packages using (let's just say) “less-than-ideal” methods`

**Comment by Daeraxa** [comment]
Thanks, updated both, the first one was one of my most frequent mistakes of changing the entire format of the sentence a billion times and leaving part of the old one hanging around, good catch.

**Comment by confused-Techie** [comment]
Awesome, this looks great @Daeraxa and I don't see anything else to comment on, super rad work.

**Comment by Daeraxa** [comment]
Updated again with @savetheclocktower's suggestions.

**Comment by savetheclocktower** [comment]
Directly edited the blurb comment to fix a misplaced parenthesis in one of your edits — I beg forgiveness. :-)

**Comment by Daeraxa** [comment]
No not a problem, the benefit of placing it here.

**Comment by DeeDeeG** [comment]
I uploaded the binaries, and it seems we are happy with the blurb now, so I'm checking those boxes off... Draft release is ready to go here on GitHub.com!

**Comment by confused-Techie** [comment]
With everything here completed, I'll go ahead and close this one out.

Huge thanks to everyone that's helped get this release to the finish line! @DeeDeeG @Daeraxa @savetheclocktower 

And want to give a small shoutout here to @asiloisad for contributing and getting their fantastic work into this release!
