### ISSUE TITLE
v1.108.0 Release Checklist

### ISSUE THREAD

**Issue by confused-Techie** [pulsar-edit/pulsar#673]
### Have you checked for existing feature requests?

- [X] Completed

### Summary

# Regular Release

- [x] ChangeLog updated (`CHANGELOG.md` and `welcome` package)
- [x] Blurb Text Complete (Comment Below)
- [x] Version Bump PR Created
- [x] Binaries Uploaded to GitHub (Including renamed binaries, and SHASUM file)
- [x] Release Posted! 🎊
- [x] Website Links updated
- [x] Blog Post
- [x] Discord Announcement
- [x] Reddit Announcement
- [x] Mastodon Announcement

### What benefits does this feature provide?

N/A

### Any alternatives?

N/A

**Comment by Daeraxa** [comment]
Blurb draft - needs a title:

# 

Welcome to our latest Pulsar release! We have some really exciting new features this month that we can't wait to share.

To kick things off, we have a brand new core package, `pulsar-updater`. We recently featured this on our monthly [Community update](https://pulsar-edit.dev/blog/20230801-Daeraxa-AugustUpdate.html#pulsar-updater-package-in-the-works) , but in case you missed it (or simply just want to read more about it), `pulsar-updater` is a new package designed to help notify users about new Pulsar releases and where they can get them. As always, we are open to feedback, especially when we have brand new functionality like this, so please let us know via any of our [social channels](https://pulsar-edit.dev/community.html) if you have anything for us.

Next, we have yet more grammars for our modern Tree-sitter implementation. If you have missed any details on this, then you can read more on [our blog](https://pulsar-edit.dev/blog/20230601-Daeraxa-JuneUpdate.html#tree-sitter-updates-are-live). The two new grammars in question are for Markdown and YAML. So what benefits does this give us? Well, for example, with Markdown, this provides significantly more accurate highlighting than the existing "Textmate" grammar; it provides HTML syntax highlighting as well as YAML frontmatter support (a common addition to Markdown documents these days, particularly for static site generators), and it allows us to clean up some of the scope names to suit a more conventional approach to naming. All these features should provide a much better Markdown writing experience in Pulsar and allow us to easily keep it up to date with anything new we might want to add in the future.

On the topic of Markdown we also have a rather large update to our `markdown-preview` package, which provides a window to display the rendered output of your Markdown documents. The big change here is the syntax highlighting displayed within code blocks specified via a "language identifier". The list of these supported identifiers was rather out of date, and the world had moved on around it, so the decision was made to bring this up to date with the behaviour that people expect from such functionality. We go into far more detail about this change in our [Blog post](https://pulsar-edit.dev/blog/20230801-Daeraxa-AugustUpdate.html#update-to-markdown-preview-language-identifiers) so have a read of that if you want to know the full details about this change.

Last, but definitely not least, we have finally begun the migration from `apm` to `ppm`. When we started the Pulsar project, one of the first things we did was rename the "Atom Package Manager" to the "Pulsar Package Manager" for obvious reasons. However, under the hood, you would still find `apm` binaries and files; this was particularly relevant for Windows users, for which there was no automatic `PATH` registration. The good news is that we have begun the transition to change them. For the time being, `apm` will remain until we can be sure we haven't hit any unforeseen issues.

And with that, we bring this to a close. As ever, a huge thank you to all of our community members and especially our donors, without whom this project just wouldn't be possible.

Until next time, happy coding, and see you amongst the stars!

  - The Pulsar Team

**Comment by Daeraxa** [comment]
Mastodon toot and reddit post can be ticked off from the list.

**Comment by confused-Techie** [comment]
@Daeraxa Thanks a ton for getting to these last few items! Appreciate everyone that helped out on here, specifically @Daeraxa and @DeeDeeG 

Plus super excited to see some less frequent faces around for this last release!

* @arite 
* @cat-master21 
* @azuledu

You all are appreciated for making this release what it is, thanks a ton!
