### ISSUE TITLE
v1.109.0 Release Checklist

### ISSUE THREAD

**Issue by confused-Techie** [pulsar-edit/pulsar#721]
### Have you checked for existing feature requests?

- [X] Completed

### Summary

# Regular Release

- [x] ChangeLog updated (`CHANGELOG.md` and `welcome` package)
- [x] Blurb Text Complete (Comment Below)
- [x] Version Bump PR Created
- [x] Binaries Uploaded to GitHub (Including renamed binaries, and SHASUM file)
- [x] Release Posted! 🎊
- [x] Update Chocolatey Release
- [x] Website Links updated
- [x] Blog Post
- [x] Discord Announcement
- [x] Reddit Announcement
- [x] Mastodon Announcement

### What benefits does this feature provide?

N/A

### Any alternatives?

N/A

### Other examples:

[Release Checklist for Pulsar](https://github.com/pulsar-edit/.github/blob/main/guides/release-checklist.md) Guide

**Comment by Daeraxa** [comment]
Blurb below. The title is meant to be a take on the fact this is our September and 9th main release as well as just the significant breadth of changes being made to improve things across the board.

# Going the whole nine yards: Get Pulsar 1.109.0 now!

Our next release has arrived, and, as ever, we are excited to share all the changes we have been making over the last month since our last release.

We have a smorgasbord of bug fixes and quality of life improvements this month that we hope will make things just that bit better overall. Many of these changes are "behind the scenes", so you may not see much evidence of them when using Pulsar, but the *lack* of any obvious changes means that we actually accomplished our goals of not disrupting the user experience.

Starting things off is one of these "background" changes, but it was a massive amount of work that was put into the project in order to move CI platform. We have a fantastic [blog post](https://pulsar-edit.dev/blog/20230903-confused-Techie-pulsars-ci.html) on the topic that really goes into the full details of this change. This release marks the first (regular) release created after this change was made, which is why we feel it is important to mention it here even though you won't see anything different in Pulsar itself.

To continue the trend of "background" changes, we have finally achieved our goal of removing all of the CoffeeScript code in the core editor and packages (a process dubbed "decaffeination") in favour of standard JavaScript. This was a goal started by the Atom team and has been a long time coming as, whilst it was good at the time, many of the features of CoffeeScript can now be found in vanilla JavaScript and migrating away from it allows a more unified codebase that is easier to maintain and lowers the barrier of entry for new contributors. Again, you won't really see anything within Pulsar itself, but this was a big achievement and we can finally draw a close to this little chapter.

Onto some changes you *will* see in Pulsar. Probably the most obvious one is our deprecation of the previous (and defunct) `autoUpdate` API. This is a follow-on from a change that first came into our `1.108.0` release to add the new core package `pulsar-updater`. You can read more about that particular change in the previous [release notes](https://pulsar-edit.dev/blog/20230816-DeeDeeG-v1.108.0.html#what-is-new-in-1-108-0). The most obvious result of this is the removal of the message on the `about` page telling you about automatic updates. This has instead been replaced with a link to the Readme of the `pulsar-updater` package reflecting the new situation.

On the topic of the `about` package, we have some nice quality of life changes. The first of which is a change to how we link to the changelog/release notes. Previously, this would link to the changelog state as it was at that specific release. We have changed this to instead link to the relevant section on our `master` branch changelog. This not only allows us to properly support our rolling releases but also gives our regular releases quick access to look at upcoming changes. We also have a nice little update to improve the responsiveness of the pane when displayed in a narrow format; no longer do things get shoved and squished out of place.

Now onto some bug fixes. The first one here regards a race condition that was found in our `autocomplete-plus` package, which was causing some weird situations where the suggestion list would open, close, then open again. This has now been fixed (with some handy assistance from the core package `keyboard-resolver` to help narrow down the problem).

The next is specific to Windows users, where the Pulsar logo was not being shown (and was being replaced with a default blank icon) when Pulsar was set to be the file handler for selected file types. This has now been solved, and the logo should be displaying correctly.

To finish things off, we have one change that improves resource usage quite considerably. However, in this case, we aren't talking about memory or CPU, but our cloud compute costs. What we found is that unnecessary requests were being made to our backend services by the `settings-view` package (which, amongst other things, is responsible for package management) for Pulsar's core packages. As the core packages aren't really designed to be updated between versions (that is why we have our [rolling release](https://pulsar-edit.dev/download.html#rolling-release)) there is no need to poll the backend for information such as the number of downloads or stargazers. The upshot of this change is that we are now saving a not-insignificant amount of money in backend costs. As this whole project is only possible due to our generous donors in the first place, this change means we can make better use of these funds that have been freed up. As always, our costs and expenses are transparent and open on our [Open Collective](https://opencollective.com/pulsar-edit) should you wish to see the effect.

And that just about draws things to a close for this release. We have had a particularly busy month with some rather significant changes to all kinds of areas of Pulsar, so we hope you enjoy the update. As ever, a huge thank you to our generous donors and community, without whom this project would not be possible.

Until next time, happy coding, and see you amongst the stars!

  - The Pulsar Team

**Comment by Daeraxa** [comment]
# Short version

Our next release has arrived, and, as ever, we are excited to share all the changes we have been making over the last month. We have a smorgasbord of bug fixes and QoL improvements for you this time.

We recently put in a massive amount of effort in order to move CI platform. We have a fantastic blog post on https://pulsar-edit.dev/blog on the topic that goes into the full details of this change.

We have achieved our goal of removing all of the CoffeeScript code in the core editor and packages (a process dubbed "decaffeination") in favour of standard JavaScript.

The previous (and defunct) `autoUpdate` API has been deprecated in favour of our new `pulsar-update` core package.

In our `about` package, we have changed the way we link to the changelog, which now links to the relevant section on our `master` branch changelog. We have also updated the responsiveness of the pane when displayed in a narrow format.

We have fixed a bug causing a race condition that was found in our `autocomplete-plus` package, which was causing some weird situations where the suggestion list would open, close, then open again.

A Windows-specific bug has also been fixed where the Pulsar logo was not being shown when Pulsar was set to be the file handler for selected file types.

Unnecessary requests were being made to our backend services by the `settings-view` package for Pulsar's core packages. As we don't need to poll the backend for core packages, we no longer do so. The upshot of this change is that we are now making some savings in backend costs, which means we can make better use of our funds.

We have had a particularly busy month with some rather significant changes to all kinds of areas of Pulsar, so we hope you enjoy the update. As ever, a huge thank you to our generous donors and community, without whom this project would not be possible.

**Comment by confused-Techie** [comment]
@Daeraxa I've honestly gotta say I feel like this is on of your top write ups so far. Even though I was around for all these changes it absolutely captured my interest. Super awesome work

**Comment by Daeraxa** [comment]
Mastodon: https://fosstodon.org/@pulsaredit/111075115680080180
Reddit: https://www.reddit.com/r/pulsaredit/comments/16k7pjq/going_the_whole_nine_yards_get_pulsar_11090_now/
Lemmy: https://lemmy.ml/post/5013615

**Comment by confused-Techie** [comment]
@Daeraxa Thanks for getting the socials updated, and just merged your website PR.

But we gotta remember to add Lemmy to our above checklist.

But with everything checked off, lets go ahead and close this one.

Thanks to everyone that helped to make this release possible!

**Comment by Daeraxa** [comment]
> But we gotta remember to add Lemmy to our above checklist.

Waaay ahead of you :) 
https://github.com/pulsar-edit/.github/pull/217
