### ISSUE TITLE
Regular Release v1.109.1 Checklist

### ISSUE THREAD

**Issue by confused-Techie** [pulsar-edit/pulsar#765]
### Have you checked for existing feature requests?

- [X] Completed

### Summary

# Regular Release

- [ ] ChangeLog updated (`CHANGELOG.md` and `welcome` package)
- [ ] Blurb Text Complete (Comment Below)
- [ ] Version Bump PR Created
- [ ] Binaries Uploaded to GitHub (Including renamed binaries, and SHASUM file)
- [ ] Release Posted! 🎊
- [ ] Update Chocolatey Release
- [ ] Website Links updated
- [ ] Blog Post
- [ ] Discord Announcement
- [ ] Reddit Announcement
- [ ] Mastodon Announcement

### What benefits does this feature provide?

n/a

### Any alternatives?

n/a

**Comment by confused-Techie** [comment]
Cirrus binaries are currently being built for this tag over on [Cirrus](https://cirrus-ci.com/build/5786686014095360).

**Comment by Daeraxa** [comment]
Blurb text below. As ever is silly o'clock in the morning for me so the tag line is just what my brain decided was vaguely funny and appropriate. As ever feel free to edit any and all of the below for the actual release.

# Armed with a big 'ol can of Raid: Pulsar 1.110.0 is available now!

Here we are with another Pulsar release, and this month we have quite a number of fixes and improvements. This time around, the focus has really been on bug fixes in order to improve the overall experience.

Starting with changes to PPM (Pulsar Package Manager), it has been updated to use a newer version of `node-gyp` (a tool for compiling native modules for node.js), which will allow use of newer C/C++ compiler toolchains as well as newer versions of Python, namely 3.11, which introduced an issue for PPM requiring downgrading to 3.10. For Windows users, it also now supports Visual Studio 2022! We previously covered (part of) this topic in one of our community update [blog posts](https://pulsar-edit.dev/blog/20230801-Daeraxa-AugustUpdate.html#moving-ppm-to-our-own-npm-fork) in a bit more detail, so be sure to have a read of that too.

On the topic of PPM, the decaffeination (conversion of CoffeeScript to JavaScript) has now been completed thanks to community member [@nemokosch/@twocolours](https://github.com/twocolours). In the [last release](https://pulsar-edit.dev/blog/20230916-Daeraxa-v1.109.0.html), we announced this had been completed in the core editor and packages; now this has been extended to PPM!

Onto Pulsar itself: we have a few new features that have been added. The first is a new autocomplete API that works on ranges rather than the previous prefix system, which will improve LSP support. (And on the topic of autocomplete, if anyone had been editing EJS files and noticed errors popping up, these have now been greatly reduced in this update).

Onto the fixes. This first one solves an issue where, if you attempted to start Pulsar with an invalid configuration file, then it would silently fail but still present a running process. Error checking has now been added so that the error can actually be exposed to the user.

Next, we have a problem introduced with our `snippets` package update, which now includes variables indicated by a `$`, which is also used by PHP, so some escaping of these characters needed to be added.

And lastly, we had a problem with macOS binary signing in version '1.109.0'; this was already covered in the last [community update](https://pulsar-edit.dev/blog/20231004-Daeraxa-OctoberUpdate.html#macos-binary-signing-issues), and now this fix applies to our regular releases.

And that just about covers things for this release. We hope you have enjoyed reading this and continue to enjoy using Pulsar. As ever, a huge thank you to our generous donors and community, without whom this project would not be possible.

Until next time, happy coding, and see you amongst the stars!

  - The Pulsar Team

## short version (discord compatible)

Here we are with another Pulsar release, and this month we have quite a number of fixes and improvements. This time around, the focus has really been on bug fixes in order to improve the overall experience.

Starting with changes to PPM (Pulsar Package Manager), it has been updated to use a newer version of `node-gyp` (a tool for compiling native modules for node.js), which will allow use of newer C/C++ compiler toolchains as well as newer versions of Python. For Windows users, it also now supports Visual Studio 2022!

On the topic of PPM, the decaffeination (conversion of CoffeeScript to JavaScript) has now been completed thanks to community member [@nemokosch/@twocolours](https://github.com/twocolours).

Onto Pulsar itself. The first is a new autocomplete API that works on ranges rather than the previous prefix system, which will improve LSP support for this package. (And on the topic of autocomplete, if anyone had been editing EJS files and noticed errors popping up, these have now been greatly reduced in this update).

Onto the fixes. This first one solves an issue where, if you attempted to start Pulsar with an invalid configuration file, then it would silently fail but still present a running process. Error checking has now been added so that the error can actually be exposed to the user.

Next, we have a problem introduced with our `snippets` package update, which now includes variables indicated by a `$`, which is also used by PHP, so some escaping of these characters needed to be added.

And lastly, we had a problem with macOS binary signing in version '1.109.0'; this was already covered in the last community update, and now this fix applies to our regular releases.

And that just about covers things for this release. As ever, a huge thank you to our generous donors and community, without whom this project would not be possible.

## short short version (for rootin' and tootin')

Here we are with another Pulsar release, and this month we have quite a number of fixes and improvements. This time the focus has really been on bug fixes in order to improve the overall experience.

We have updates to PPM for newer toolchain compatibility, a new Autocomplete API, better error handling for a crash at launch with invalid config and a fix for PHP snippets.

**Comment by confused-Techie** [comment]
@Daeraxa Fantastic work here.
Other than an inclusion of @GuilleW on the PPM decaf work (Since 2colours PRs were based on those commits which became painfully out of sync) I think this is perfect! Also, totally gonna vote to keep the title, it's beautiful!

**Comment by Daeraxa** [comment]
Thanks! I've updated the discord short one (remembered markdown links dont work anyway so removed them in favour of just bolding them so it didn't go overlength).

**Comment by Daeraxa** [comment]
With the release published I've done the Discord announcement, Reddit post, Lemmy post (I thought I added this to the checklist...) and Mastodon toot.

**Comment by Daeraxa** [comment]
I've created the chocolately repo issue out of curiosity (https://github.com/pulsar-edit/pulsar-chocolatey/issues/24) but realised I don't have permissions to add the release tag so can't progress from there.

**Comment by confused-Techie** [comment]
New chocolatey version has been published!

**Comment by Daeraxa** [comment]
Website links and blog post up - https://github.com/pulsar-edit/pulsar-edit.github.io/pull/246

**Comment by confused-Techie** [comment]
Looks like everything here is covered.
Huge thanks to those that helped get things sorted!
