### ISSUE TITLE
Pulsar v1.111.0 Release Checklist

### ISSUE THREAD

**Issue by confused-Techie** [pulsar-edit/pulsar#806]
### Have you checked for existing feature requests?

- [X] Completed

### Summary

# Regular Release

- [x] ChangeLog updated (`CHANGELOG.md` and `welcome` package)
- [x] Blurb Text Complete (Comment Below)
- [x] Version Bump PR Created
- [x] Binaries Uploaded to GitHub (Including renamed binaries, and SHASUM file)
- [x] Release Posted! 🎊
- [x] Update Chocolatey Release
- [x] Website Links updated
- [x] Blog Post
- [x] Discord Announcement
- [x] Reddit Announcement
- [x] Mastodon Announcement
- [x] Lemmy Announcement

### What benefits does this feature provide?

N/A

### Any alternatives?

N/A

**Comment by Daeraxa** [comment]
Blurbs. As ever feel free to edit if needed when I'm asleep. You have my permission.

---

# If you're API and you know it, clap your hands: Pulsar 1.110.0 is available now!

Welcome to a new Pulsar regular release. This time we have a big new addition to Pulsar's API along with our usual set of bug fixes (with some fantastic community contributions).

One of our major changes is the new `UI` API we have added to the 'atom' global class. You can read about this in detail in our recent [blog post](https://pulsar-edit.dev/blog/20231109-Daeraxa-NovemberUpdate.html#new-ui-api) but essentially, this allows us to unify the way we render things in Pulsar. For this release, we have a new 'markdown' object that means packages (both core and community) no longer have to worry about performing Markdown rendering and instead can offload it to Pulsar itself. This allows us to create a unified way to render Markdown by using a single set of dependencies. We also took the opportunity to move from the previous [marked](https://marked.js.org/) library to the [markdown-it](https://github.com/markdown-it/markdown-it) parser we are already using on the [Pulsar Package Registry](https://web.pulsar-edit.dev/). As an added bonus, we also get to save some space on the installation size!

On that last topic, we have found a way to reduce Pulsar's installed size by ~35.5 MB by deduping some dependencies and otherwise performing some fine tuning on them.

Next, we have a fix for a really tricky bug that has been around since the Atom days, which we logged on our own repo almost a year ago. The problem is that it has been devilishly difficult to find a perfect set of reproduction steps. Thankfully, we have now managed to do this (with a great deal of help from one of our community members, [@asiloisad/@bacadra](https://github.com/bacadra/)) and have a fix. This was a problem that would occasionally show up when a hidden `input` element used in the text editors would be focused when out of view, causing the screen to be "misaligned" or otherwise "shifted".

And on the theme of community, we have two issue reports and subsequent bug fixes by community members. The first is by [@danfuzz](https://github.com/danfuzz) to fix a problem in our `bash` Tree-sitter grammar where ANSI C quoted strings were not being properly highlighted as actual strings. The second is by [@kiskoza](https://github.com/kiskoza) who discovered a problem with our (relatively) recently introduced `pulsar-updater` package, which notifies you if a new release of Pulsar is available. The bug in question was a problem with the "Dismiss this version" button, which was not caching correctly and would therefore "forget" that somebody had requested to not be notified for that version again.

We hope you enjoyed reading about this update as much as we hope you continue to enjoy using Pulsar. As ever, a huge thank you to our generous donors and community, without whom this project would not be possible.

Until next time, happy coding, and see you amongst the stars!

  - The Pulsar Team

## Short version for those who don't want to pay for Discord Nitro

Welcome to a new Pulsar regular release. This time we have a big new addition to Pulsar's API along with our usual set of bug fixes (with some fantastic community contributions).

One of our major changes is the new `UI` API we have added to the 'atom' global class. You can read about this in detail in our recent [blog post](https://pulsar-edit.dev/blog/20231109-Daeraxa-NovemberUpdate.html#new-ui-api) but essentially, this allows us to unify the way we render things in Pulsar. We now have a new `markdown` object that means packages (both core and community) now have a unified way to render Markdown by using a single set of dependencies.

We have found a way to reduce Pulsar's installed size by ~35.5 MB by deduping some dependencies and otherwise performing some fine tuning on them.

Next, we have a fix for a really tricky bug that has been around since the Atom days. The problem is that it has been devilishly difficult to find a perfect set of reproduction steps. Thankfully, we have now managed to do this (with a great deal of help from one of our community members, [@asiloisad/@bacadra](https://github.com/bacadra/)) and have a fix. This was a problem that would occasionally show up when a hidden `input` element used in the text editors would be focused when out of view, causing the screen to be "misaligned" or otherwise "shifted".

And some more community member contributions! The first is by [@danfuzz](https://github.com/danfuzz) to fix a problem in our `bash` Tree-sitter grammar where ANSI C quoted strings were not being properly highlighted. The second is by [@kiskoza](https://github.com/kiskoza) who discovered a problem with our  `pulsar-updater` package, which notifies you if a new release of Pulsar is available. It was found that the "Dismiss this version" button was not caching correctly and would therefore "forget" that somebody had requested to not be notified for that version again.

## Fun-sized version for the toots

Welcome to a new Pulsar regular release. This time we have a big new addition to Pulsar's API along with our usual set of bug fixes (with some fantastic community contributions).

This time we have a brand new API, a reduction in Pulsar's installed size, a fix for a really tricky and annoying bug and some fixes from the community.

**Comment by DeeDeeG** [comment]
Thank you @Daeraxa for the blurbening!

> Short version for those who don't want to pay for Discord Nitro

Heh.

> Fun-sized version for the toots

I suppose we can take the "Welcome to a new Pulsar regular release" and then then second version of the remaining parts "This time we have a brand new API, a reduction in Pulsar's installed size, a fix for a really tricky and annoying bug and some fixes from the community."

Since otherwise that sentence is effectively repeated twice.

What's the character limit there?

**Comment by Daeraxa** [comment]
> Since otherwise that sentence is effectively repeated twice.

No, this is a pasting problem, hang on...

**Comment by Daeraxa** [comment]
Website links and blog done

**Comment by confused-Techie** [comment]
> Website links and blog done

Just merged that one, thanks!
