### ISSUE TITLE
Release Checklist for 1.112.0 - PENDING Chocolatey Release Issues

### ISSUE THREAD

**Issue by confused-Techie** [pulsar-edit/pulsar#834]
### Have you checked for existing feature requests?

- [X] Completed

### Summary

# Regular Release

- [x] ChangeLog updated (`CHANGELOG.md` and `welcome` package)
- [x] Blurb Text Complete (Comment Below)
- [x] Version Bump PR Created
- [x] Binaries Uploaded to GitHub (Including renamed binaries, and SHASUM file)
- [x] Release Posted! 🎊
- [ ] Update Chocolatey Release
- [x] Website Links updated
- [x] Blog Post
- [x] Discord Announcement
- [x] Reddit Announcement
- [x] Mastodon Announcement
- [x] Lemmy Announcement

### What benefits does this feature provide?

n/a

### Any alternatives?

n/a

**Comment by Daeraxa** [comment]
As normal, feel free to edit as much or as little as you want, it is rather late (early??) here and I'm completely spent at this point :)

---

# Christmas has come early: Pulsar 1.112.0 is available now!

Welcome to our 12th regular release! It has been exactly a year since we put out [our first tagged release](https://pulsar-edit.dev/blog/20221215-confused-Techie-v1.100.1-beta.html) and development continues. This month we have some new soft-wrapping options, some long overdue updates to PPM, improvements to our "GitHub" package, a new `fuzzyMatcher` API and our usual slew of bug fixes.

Let's start with a feature added by community member [@Trigan2025](https://github.com/Trigan2025). There are now new options for the "soft wrapping" feature that allows Pulsar to automatically show or hide the soft wrap guide line based on your soft wrap settings. You can find this new option within `wrap-guide` package settings.

We have a number of new PPM changes, including better and more secure network handling and converting PPM's code to async. You can read about this second change in much more detail in a recent [blog post](https://pulsar-edit.dev/blog/20231004-Daeraxa-OctoberUpdate.html#converting-ppm-s-code-from-callbacks-to-async) we made. We have also taken the opportunity to do some out-of-season spring cleaning to tidy up the repo and get rid of old, unused dependencies, as well as some general maintenance.

On to our GitHub package, we found that we had a rather common issue with people not being able to log into their GitHub account via the package. Essentially, it was possible to set scopes in such a way that, although permissions were technically granted, Pulsar was unable to read the scopes and refused to log in. To solve this, we have updated the package to provide feedback and improved the scope checking logic. We also updated the link to the Personal Access Token page to include by default the scopes that Pulsar requires.

In a similar vein to last month's new `UI` API, we have another new 'atom' global class that all packages can now take advantage of. This time it is `fuzzyMatcher` which will allow packages to use Pulsar's `fuzzy-finder` module without needing to bundle it into their own packages.

And to finish off with a bug fix, an issue was found where Pulsar wasn't correctly inheriting the directory from which the `pulsar` binary was being run, leading to some slightly odd behaviour.

It is hard to believe that it has been an entire year since we created our first tagged release of Pulsar and we never would have managed to get to this milestone without the amazing support from our donors and our community, so as ever, a massive thank you to everyone who has allowed us to get this far!

Until next time (and next year!), happy coding, and see you amongst the stars!

- The Pulsar Team

---

## I ain't paying just to get some flashing emotes

Welcome to our 12th regular release! It has been exactly a year since we put out our first tagged release and development continues. This month we have some new soft-wrapping options, some long overdue updates to PPM, improvements to our "GitHub" package, a new `fuzzyMatcher` API and our usual slew of bug fixes.

Let's start with a feature added by community member [@Trigan2025](https://github.com/Trigan2025). There are now new options for the "soft wrapping" feature within the `wrap-guide` package that allows Pulsar to automatically show or hide the soft wrap guide line based on your soft wrap settings.

We have a number of new PPM changes, including better and more secure network handling and converting PPM's code to async. You can read about this second change in much more detail in October's community update blog post. We have also taken the opportunity to do some out-of-season spring cleaning to tidy up the repo and get rid of old, unused dependencies, as well as some general maintenance.

On to our GitHub package, we found that we had a rather common issue with people not being able to log into their GitHub account via the package due to some specific scope settings. We have updated the package to provide feedback and improved the scope checking logic as well as updating the link to the Personal Access Token page.

In a similar vein to last month's new `UI` API, we have another new 'atom' global class that all packages can now take advantage of. This time it is `fuzzyMatcher` which will allow packages to use Pulsar's `fuzzy-finder` module without needing to bundle it into their own packages.

And to finish off with a bug fix, an issue was found where Pulsar wasn't correctly inheriting the directory from which the `pulsar` binary was being run, leading to some slightly odd behaviour.

https://github.com/pulsar-edit/pulsar/releases/tag/v1.111.0

---

## 🐘🎺

Welcome to our 12th regular release! It has been exactly a year since we put out our first tagged release and development continues. This month we have some new soft-wrapping options, some long overdue updates to PPM, improvements to our "GitHub" package, a new `fuzzyMatcher` API and our usual slew of bug fixes.

**Comment by DeeDeeG** [comment]
> 🐘🎺

We toot at dawn

**Comment by DeeDeeG** [comment]
Edited this paragraph:

> In a similar vein to last month's new `UI` API, we have another new 'atom' global class that all packages can now take advantage of. This time it is `fuzzyMatcher` which will allow packages to use Pulsar's `fuzzy-finder` module without needing to bundle it into their own packages.

to:

> Continuing with the theme of last month's new "UI" API, we have another new API that all packages can now take advantage of. This time it is `ui.fuzzyMatcher` which will allow packages to use Pulsar's `fuzzy-finder` module without needing to bundle it into their own packages.

**Comment by Daeraxa** [comment]
Website links + blog post PR: https://github.com/pulsar-edit/pulsar-edit.github.io/pull/257

**Comment by Daeraxa** [comment]
Socials posts:

Reddit: https://www.reddit.com/r/pulsaredit/comments/18jvmg7/christmas_has_come_early_pulsar_11120_is/?  
Lemmy: https://lemmy.ml/post/9396885
🐘🎺: https://fosstodon.org/@pulsaredit/111591208000403797

**Comment by confused-Techie** [comment]
Thanks for getting those all handled @Daeraxa!
Also gotta say, I love the links being added to this issue, makes things easy to go back on or check, gonna cross those off now

**Comment by confused-Techie** [comment]
But since we are having some issues with the chocolatey release this time around, I'm gonna leave this issue open until those are sorted, and quickly update the issue title, for anyone curious

**Comment by DeeDeeG** [comment]
Version 1.112.0 is still not approved, for some not obvious reason.

1.112.1 is approved though. 🎉

(Not sure what the difference is that made this pass but the other version not pass. I think we can leave one more comment asking them to manually review it without checking the "automatically re-run checks" box and maybe they'll review it then? But I'm about as much inclined to just let 1.112.1 be the latest version and not worry about getting 1.112.0 published on Chocolatey.)

**Comment by confused-Techie** [comment]
@DeeDeeG Totally agree we give it one more go before just yanking this release on Chocolatey.

But like you mentioned, what changed between these two versions for one to be fine, and the other to fail? Especially considering after setting up the chocolatey environment I couldn't replicate the failures they are seeing at all.

**Comment by DeeDeeG** [comment]
Do we eventually close this issue, or does it linger on like the still-pending 1.112.0 upload to Chocolatey? (1.112.1 is fine, what the difference is to them remains a mystery.)

We could put in an effort to give it one last go at an automated re-run, but beyond that I'd say can the effort and let Chocolatey not have the version the (now superseded) version their automated system doesn't seem to want in the first place.

**Comment by confused-Techie** [comment]
After working with the chocolatey team, they've opted to close this release, and we let Pulsar 1.112.1 carry on as the next viable version. Meaning it's fully expected for there not to exist a Pulsar 1.112.0 on Chocolatey.

**Comment by Daeraxa** [comment]
Did they give a reason as to why it couldn't be submitted? Just thinking for what we do when we don't have a corrective release to solve the issue.

**Comment by confused-Techie** [comment]
@Daeraxa I'll go ahead and copy the snippet in the update email we got about this one:

> 'pulsar' is Rejected.
> gep13 left the following comment(s):
>
> To allow you to move forward with newer package versions, let's just reject this package version, and not waste any more cycles on it.
>
> Thanks for sticking with us through this!
> Status Change - Changed status of package from 'submitted' to 'rejected'.
>
> The package was rejected by gep13 on 08 Jan 2024.

So nobody really seems to know why it was failing the automatic verification, I know I absolutely spent way too much time testing things myself on their testing environment, never once able to get things to fail. So I'm really not too sure what went wrong, but nor do they seem to be.

Very likely what we could do in the future, is do a patch release like @DeeDeeG suggested, and keep it only for Chocolatey.

---

Although if anybody else would like to try and do a post-mortem on this in greater detail I'll go ahead and provide all the details I can.

* The [Automated PR](https://github.com/pulsar-edit/pulsar-chocolatey/pull/29) that bumped Pulsar's version on Chocolatey to 1.112.0
* The first [verification failure link](https://gist.github.com/choco-bot/fd6693b7bae52abffce4c0099beb2ac9)
* The second [verification failure link](https://gist.github.com/choco-bot/2c181596c5bd2375a697d9d0873b3ac7)
* The third [verification failure link](https://gist.github.com/choco-bot/05fb27ec4977eddac3c236f145ac8662)

Then to confirm when I manually tested this in their verification environment, I tried not only the `nupkg` generated from the above PR, I generated a new one and tried that as well, and I even downloaded the remote `nupkg` that Chocolatey had and tested that. I couldn't get a single one to fail, with all of them passing just fine for me.

But then of course when we submitted version 1.112.1 of Pulsar, it passed the automated verification without issue, just like every other version prior to this event.

Hope someone can try to make some sense of this, but studying the logs of the runs that failed, and the logs of the successful runs I had, I wasn't able to find any major difference. But even so, if helpful here's the details of Pulsar 1.113.0's passing [verification link](https://gist.github.com/choco-bot/397bbea8a7c595ca1dbaecf3ee7f8a0e).

Good luck to whoever takes a look, and would love to hear if there's something they can find of interest.

**Comment by DeeDeeG** [comment]
I'm really late in responding to this, but thank you for the write-up! Good to have some transparency about what was said, even if we can't have a satisfying technical explanation of what went wrong that time we have it pretty well documented, as well as we can anyway.
