### ISSUE TITLE
Release Checklist for Pulsar v1.113.0

### ISSUE THREAD

**Issue by DeeDeeG** [pulsar-edit/pulsar#863]
# Regular Release v1.113.0

- [x] ChangeLog updated (`CHANGELOG.md` and `welcome` package)
- [x] Blurb Text Complete (Comment Below)
- [x] Version Bump PR Created
- [x] Binaries Uploaded to GitHub (Including renamed binaries, and SHASUM file)
- [x] Release Posted! 🎊
- [x] Update Chocolatey Release
- [x] Website Links updated
- [x] Blog Post
- [x] Discord Announcement
- [x] Reddit Announcement
- [x] Mastodon Announcement
- [x] Lemmy Announcement

**Comment by Daeraxa** [comment]
Blurb

## Unlucky for some, but not us. Our 13th release, Pulsar 1.113.0, is available now!

Welcome to our first release of 2024! This is our 13th main release; let's just hope we aren't cursed by the number. This month we are enabling a feature by default that has been in the works for a long time and is a major step in moving Pulsar to current versions of Electron. We also have a significant update to our `symbols-view` package and a number of bug fixes as per usual.

First up is something we have been mentioning in the last few community update blog posts and otherwise hinting about for a while. Back in Pulsar 1.106.0, released in July last year, we added a new setting called `Use Modern Tree-Sitter Implementation` that would enable a brand new implementation of [Tree-sitter](https://tree-sitter.github.io/tree-sitter/) within Pulsar. If you want to know more about the history of this change, then have a look at our detailed [blog post](https://pulsar-edit.dev/blog/20230601-Daeraxa-JuneUpdate.html#tree-sitter-updates-are-live) on the topic as well as [@savetheclocktower](https://github.com/savetheclocktower)'s fantastic [blog post series](https://pulsar-edit.dev/tag/tree-sitter/). A huge thank you to everyone who contributed to this feature by testing it out and submitting bug reports and pull requests, these contributions have led to this moment where we can finally activate it by default. The reason we have done this is in order to eventually move to modern versions of Electron, for which the old tree-sitter implementation is simply not compatible. We have had this as an option while we worked out the most egregious kinks in the system, but we are in a position where we feel it is strong enough to enable by default. If you encounter any significant issues with the new system, there is a new option `Use Legacy Tree-sitter Implementation` that will revert to the old system. It would be great if any problems with the new system could be brought to our attention via any of our [social channels](https://pulsar-edit.dev/community.html) so we can look to fix any issues that have yet to be encountered by us.

We have a rather significant update to our `symbols-view` package. This package is used to display symbols within Pulsar (e.g. function definitions) and allows you to navigate your code via those symbols. This package has had a rather major overhaul and now follows the standard "provider/consumer" model as many other Pulsar packages do. In particular, this allows for packages to provide symbols to `symbols-view`, such as Tree-sitter grammars, via the new `symbol-provider-tree-sitter` package. The upshot of this, combined with the new Tree-sitter implementation, is that there will be a much richer and more accurate display of symbols in your project. More information can be found in the [pull request](https://github.com/pulsar-edit/pulsar/pull/829) for this change.

A new Tree-sitter PHP grammar has been added to Pulsar as part of ongoing Tree-sitter grammar upgrades and improvements, which includes some contributions from community member [@claytonrcarter](https://github.com/claytonrcarter) who had a parser for PHPDoc allowing us to highlight documentation comments in PHP in a similar vein to JSDoc injection JS/TS files.

On to some bug fixes. We had an issue reported about the `github` package that showed a problem with the rendering of the diff view display. This seems to have been due to the code for the package running before the editor was even visible. The fix here was to make sure the editor is actually visible before running this code.

Next, we have a fix to the `find-and-replace` package caused by an odd interaction between the package and the `Preserve Case During Replace` option, causing an error to appear when using empty strings as input (as an empty string cannot be capitalized).

And last, we have a change to the default behavior of rendering emojis in Markdown as part of the new `UI` API. This issue was discovered due to an unwelcome (but admittedly rather apt) 😡 in the middle of an error message popup. While [the error](https://github.com/pulsar-edit/pulsar/pull/850) was rather hilarious, we did decide that it needed to be banished by default for the sake of one of our team members' sanity (and to reduce unnecessary obfuscation of errors, of course).

And that is all we have for you right now. We hope you enjoy this new release and here is to another 12 months of Pulsar!

Until next time, happy coding, and see you amongst the stars!

- The Pulsar team

## I don't know what Nitro is and at this point I'm too afraid to ask

Welcome to our first release of 2024! This is our 13th main release; let's just hope we aren't cursed by the number. This month we are enabling the modern Tree-sitter implementation by default, adding a significant update to our `symbols-view` package and fixing a number of bugs as per usual.

Back in Pulsar 1.106.0, we added a new setting called `Use Modern Tree-Sitter Implementation` that would enable a brand new implementation of Tree-sitter) within Pulsar. We have now activated this option by default. If you want to know more about this change, then have a look at our detailed [blog post](https://pulsar-edit.dev/blog/20230601-Daeraxa-JuneUpdate.html#tree-sitter-updates-are-live) on the topic.

We have a significant update to our `symbols-view` package. This package is used to display symbols within Pulsar (e.g. function definitions) and allows you to navigate your code via those symbols. This package now follows the standard "provider/consumer" model, as many other Pulsar packages do. This, combined with the new Tree-sitter implementation, means that there will be a much richer and more accurate display of symbols in your project.

A new Tree-sitter PHP grammar has been added to Pulsar as part of ongoing Tree-sitter grammar upgrades and improvements, which includes some contributions from community member @claytonrcarter who had a parser for PHPDoc allowing us to highlight documentation comments in PHP.

We had an issue reported about the `github` package that showed a problem with the rendering of the diff view display. This was due to the code for the package running before the editor was even visible.

A fix has been made to the `find-and-replace` package, which displayed an odd interaction between the package and the `Preserve Case During Replace` option, causing an error to appear when using empty strings as input.

## Show yourself. Show yourself. I want to see everything you're made of

Welcome to the release of Pulsar 1.113.0, our first release of 2024. For this release we have enabled our modern Tree-sitter implementation by default, a new Tree-sitter PHP grammar, a huge update to our 'symbols-view' package, a bunch of bug fixes and an issue where we banish 😡 to the Netherrealm.

**Comment by savetheclocktower** [comment]
> On to some bug fixes. We had an issue reported about the `github` package that showed a problem with the rendering of the diff view display. This seems to have been due to the code for the package running before the editor was even visible. The fix here was to make sure the editor is actually visible before running this code.

I'd replace this with

> On to some bug fixes. We had an issue reported about the `github` package that showed a problem with the rendering of the diff view display. This seems to have been due to a code path in our `TextEditor` component that would sometimes try to perform measurements on things that weren't necessarily visible. The fix here, simple as it seems, was to defer those measurements until we could be sure the editor was visible.

Ain't perfect, but I'm too tired to think of the perfect phrasing!

**Comment by Daeraxa** [comment]
Blog post + download links PR
https://github.com/pulsar-edit/pulsar-edit.github.io/pull/260

**Comment by Daeraxa** [comment]
Reddit post: https://www.reddit.com/r/pulsaredit/comments/197u3c9/unlucky_for_some_but_not_us_our_13th_release/?

Toot: https://fosstodon.org/@pulsaredit/111763778171549833

Lemmy: https://lemmy.ml/post/10608348

**Comment by confused-Techie** [comment]
@Daeraxa Thanks for addressing everything you have! Looks like this issue is now good to close!
