### ISSUE TITLE
1.114.0 Release Checklist

### ISSUE THREAD

**Issue by confused-Techie** [pulsar-edit/pulsar#928]
### Have you checked for existing feature requests?

- [X] Completed

### Summary

# Regular Release

- [x] ChangeLog updated (`CHANGELOG.md` and `welcome` package)
- [x] Blurb Text Complete (Comment Below)
- [x] Version Bump PR Created
- [x] Binaries Uploaded to GitHub (Including renamed binaries, and SHASUM file)
- [x] Release Posted! 🎊
- [x] Update Chocolatey Release
- [x] Website Links updated
- [x] Blog Post
- [x] Discord Announcement
- [x] Reddit Announcement
- [x] Mastodon Announcement
- [x] Lemmy Announcement

### What benefits does this feature provide?

n/a

### Any alternatives?

n/a

**Comment by Daeraxa** [comment]
Bluurrrrrrrrrrrrrrrbs. Going to have to abandon these in order to get some sleep, feel free to change as much or as little as you like as this is very much typed out on bloodshot eyes.

## A Valentine's release bursting with love, Pulsar 1.114.0 is available now!

Welcome to a brand new Pulsar release! I think it is safe to say that this month has been one of our more eventful due to the switchover we made to the new Tree-sitter implementation. This release features a lot of updates and fixes for this new implementation, thanks to all the feedback we got from the community. We also have a number of bug fixes and new features to introduce, such as restoring compatibility with older Linux distributions and a new `ppm` command

As mentioned above, we have quite a few changes relating to our new Tree-sitter implementation that we made default in Pulsar 1.113.0. Not only do we have quite a few fixes and updates to make sure the new implementation isn't a regression from the legacy implementation. One such update is restoring support for the [semanticolor](https://web.pulsar-edit.dev/packages/semanticolor) package, which was supported by the previous implementation. Otherwise, if you had any particular issue with syntax highlighting, then we hope it has now been resolved, as a lot of changes and fixes have been made in response to community feedback. If not, then please visit our ongoing ["Mega-issues"](https://github.com/pulsar-edit/pulsar/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+MEGA-ISSUE+label%3Abug) and see if your issue has been raised, and if not, please raise it there.

Back in Pulsar 1.111.0, we created a new `UI` api to make an easy and universal way for packages to interact with Pulsar. This did create a couple of small issues, which have now been resolved. One issue with the markdown implementation was the display of non-functional heading anchors when rendering a package README; the other was a small rendering bug that was causing a misalignment of content after a linebreak. We also introduced a new problem with `fuzzymatcher` that could cause the command palette to hang if it failed to highlight a match.

One issue raised a while ago was that, starting with Pulsar 1.109.0, users of older LTS Linux distributions, such as AlmaLinux 8 and RockyLinux 9, were no longer able to run Pulsar. This was due to the CI runners we use being updated to newer OSs, and therefore Pulsar was being compiled against a newer version of `glibc`. We have changed our workflows to compile Pulsar on a Debian 10 VM instead, which should resolve this problem.

It was noticed a while ago that the `github` package wasn't quite working correctly on ARM Linux systems. We have bumped the version of `dugite` (a library for `git` bindings) to resolve the problem.

Lastly, we have two new features in `ppm`. The first is a new flag `--force` that can be specified on `ppm link`, which will forcibly replace a conflicting package without needing to manually remove it. The other is an update to `ppm`'s syntax theme template so that, when generating a new syntax theme, it adds tokens that previously existed but were missing from the template.

And that is it for yet another Pulsar release. We hope you enjoy this release and look forward to the next one!

Until next time, happy coding, and see you amongst the stars!

- The Pulsar team

## No I don't want to boost your server

Welcome to a brand new Pulsar release! I think it is safe to say that this month has been one of our more eventful due to the switchover we made to the new Tree-sitter implementation. This release features a lot of updates and fixes for this new implementation, thanks to all the feedback we got from the community. We also have a number of bug fixes and new features to introduce, such as restoring compatibility with older Linux distributions and a new `ppm` command

We have quite a few changes relating to our new Tree-sitter implementation such as restoring support for the semanticolor package. If you had any particular issue with syntax highlighting, then we hope it has now been resolved. If not, then please visit our ongoing "Mega-issues" on the Pulsar repo.

We have some fixes for the new `UI` api introduced in Pulsar 1.111.0. One issue was the display of  heading anchors when rendering a package README; another was a small rendering bug that was causing a misalignment of content after a linebreak. A new problem was also found with `fuzzymatcher` that could cause the command palette to hang if it failed to highlight a match.

From Pulsar 1.109.0, some users of older LTS Linux distributions were no longer able to run Pulsar. This was due to  Pulsar was being compiled against a newer version of `glibc`. We now compile Pulsar on a Debian 10 VM, which should resolve this problem.

It was noticed a while ago that the `github` package wasn't quite working correctly on ARM Linux systems. We have bumped the version of `dugite` (a library for `git` bindings) to resolve the problem.

We also have two new features in `ppm`. The first is a new flag `--force` that can be specified on `ppm link`, to forcibly replace a conflicting package. The other is an update to `ppm`'s syntax theme template so that it adds tokens that previously existed but were missing from the generated theme.

## t00t

Welcome to a brand new Pulsar release!This release features a lot of updates and fixes for our modern Tree-sitter implementation, an assorted bag of bug fixes and some new features to introduce, such as restoring compatibility with older Linux distributions and a new `ppm` command

**Comment by DeeDeeG** [comment]
A second pass of the full-length blurb:

## A Valentine's release bursting with love, Pulsar 1.114.0 is available now!

Welcome to a brand new Pulsar release! I think it is safe to say that this month has been one of our more eventful due to the switchover we made to the new Tree-sitter implementation. This release features a lot of updates and fixes for this new implementation, thanks to all the feedback we got from the community. We also have a number of \[other\] bug fixes and new features to introduce, such as restoring compatibility with older Linux distributions ~~and a new ppm command~~ \[and a new flag for an old favorite `ppm` command.\]

As mentioned above, we have quite a few changes relating to our new Tree-sitter implementation that we made default in Pulsar 1.113.0. ~~Not only do we have quite a few~~ \[First of all, we have some\] fixes and updates to make sure the new implementation isn't a regression from the legacy implementation. One such update is restoring support for the [semanticolor](https://web.pulsar-edit.dev/packages/semanticolor) package, which was supported by the previous implementation. Otherwise, if you had any particular issue with syntax highlighting, then we hope it has now been resolved, as a lot of changes and fixes have been made in response to community feedback. If not, then please visit our ongoing ["Mega-issues"](https://github.com/pulsar-edit/pulsar/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+MEGA-ISSUE+label%3Abug) and see if your issue has been raised, and if not, please raise it there.

Back in Pulsar 1.111.0, we created a new `UI` api to make an easy and universal way for packages to interact with Pulsar. ~~This did create a couple of small issues~~ \[This implementation did contain a couple of small oversights\], which have now been resolved. One issue with the markdown implementation was the display of non-functional heading anchors when rendering a package README; the other was a small rendering bug that was causing a misalignment of content after a linebreak. ~~We also introduced~~ \[We had also inadvertently introduced\] a new problem with `fuzzymatcher` that could cause the command palette to hang if it failed to highlight a match.

One issue raised a while ago was that, starting with Pulsar 1.109.0, users of older LTS Linux distributions, such as AlmaLinux 8 and RockyLinux 9, were no longer able to run Pulsar. This was due to the CI runners we use being updated to newer OSs, and therefore Pulsar was being compiled against a newer version of `glibc`. We have changed our workflows to compile Pulsar in a Debian 10 ~~VM~~ \[Docker container\] instead, which should resolve this problem.

It was noticed a while ago that the `github` package wasn't quite working correctly on ARM Linux systems. We have bumped the version of `dugite` (a library for \[using\] `git` \[in NodeJS and Electron\] ~~bindings~~) to resolve the problem.

Lastly, we have two new features in `ppm`. The first is a new flag `--force` that can be specified on `ppm link`, which will forcibly replace a conflicting package without needing to manually remove it. The other is an update to `ppm`'s syntax theme template so that, when generating a new syntax theme, ~~it adds tokens that previously existed but were missing from the template.~~ \[it now includes some style variables that the editor has long supported, but which were not in the template, so theme authors might have been unaware of them. (As a bonus: there are two _new_ variables supported by default in the editor, and added to the template as well! Theme authors, feel free to take advantage of these!)\]

And that is it for yet another Pulsar release. We hope you enjoy this release and look forward to the next one!

Until next time, happy coding, and see you amongst the stars!

- The Pulsar team

<details><summary><b>❗Without the editing/changes markup (just the second draft text)❗</b> (click to expand):</summary>

## A Valentine's release bursting with love, Pulsar 1.114.0 is available now!

Welcome to a brand new Pulsar release! I think it is safe to say that this month has been one of our more eventful due to the switchover we made to the new Tree-sitter implementation. This release features a lot of updates and fixes for this new implementation, thanks to all the feedback we got from the community. We also have a number of other bug fixes and new features to introduce, such as restoring compatibility with older Linux distributions and a new flag for an old favorite `ppm` command.

As mentioned above, we have quite a few changes relating to our new Tree-sitter implementation that we made default in Pulsar 1.113.0. First of all, we have some fixes and updates to make sure the new implementation isn't a regression from the legacy implementation. One such update is restoring support for the [semanticolor](https://web.pulsar-edit.dev/packages/semanticolor) package, which was supported by the previous implementation. Otherwise, if you had any particular issue with syntax highlighting, then we hope it has now been resolved, as a lot of changes and fixes have been made in response to community feedback. If not, then please visit our ongoing ["Mega-issues"](https://github.com/pulsar-edit/pulsar/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+MEGA-ISSUE+label%3Abug) and see if your issue has been raised, and if not, please raise it there.

Back in Pulsar 1.111.0, we created a new `UI` api to make an easy and universal way for packages to interact with Pulsar. This implementation did contain a couple of small oversights, which have now been resolved. One issue with the markdown implementation was the display of non-functional heading anchors when rendering a package README; the other was a small rendering bug that was causing a misalignment of content after a linebreak. We had also inadvertently introduced a new problem with `fuzzymatcher` that could cause the command palette to hang if it failed to highlight a match.

One issue raised a while ago was that, starting with Pulsar 1.109.0, users of older LTS Linux distributions, such as AlmaLinux 8 and RockyLinux 9, were no longer able to run Pulsar. This was due to the CI runners we use being updated to newer OSs, and therefore Pulsar was being compiled against a newer version of `glibc`. We have changed our workflows to compile Pulsar in a Debian 10 Docker container instead, which should resolve this problem.

It was noticed a while ago that the `github` package wasn't quite working correctly on ARM Linux systems. We have bumped the version of `dugite` (a library for using `git` in NodeJS and Electron) to resolve the problem.

Lastly, we have two new features in `ppm`. The first is a new flag `--force` that can be specified on `ppm link`, which will forcibly replace a conflicting package without needing to manually remove it. The other is an update to `ppm`'s syntax theme template so that, when generating a new syntax theme, it now includes some style variables that the editor has long supported, but which were not in the template, so theme authors might have been unaware of them. (As a bonus: there are two _new_ variables supported by default in the editor, and added to the template as well! Theme authors, feel free to take advantage of these!)

And that is it for yet another Pulsar release. We hope you enjoy this release and look forward to the next one!

Until next time, happy coding, and see you amongst the stars!

- The Pulsar team

</details>

**Comment by Daeraxa** [comment]
Website update PR here - https://github.com/pulsar-edit/pulsar-edit.github.io/pull/268

**Comment by Daeraxa** [comment]
🐘🎺 - https://fosstodon.org/@pulsaredit/111943208997316687
🐭 - https://lemmy.ml/post/12006883
💩 - https://www.reddit.com/r/pulsaredit/comments/1asjocc/a_valentines_release_bursting_with_love_pulsar/

**Comment by confused-Techie** [comment]
Thanks for the help to everywhere who made this release possible!
