### ISSUE TITLE
1.115.0 Release Checklist

### ISSUE THREAD

**Issue by DeeDeeG** [pulsar-edit/pulsar#963]
# Regular Release

- [x] ChangeLog updated (`CHANGELOG.md` and `welcome` package)
- [x] Blurb Text Complete (Comment Below)
- [x] Version Bump PR Created
- [x] Binaries Uploaded to GitHub (Including renamed binaries, and SHASUM file)
- [x] Release Posted! 🎊
- [x] Update Chocolatey Release
- [x] Website Links updated
- [x] Blog Post
- [x] Discord Announcement
- [x] Reddit Announcement
- [x] Mastodon Announcement
- [x] Lemmy Announcement

**Comment by DeeDeeG** [comment]
<details><summary>The <code>git log --oneline --graph</code> output since 1.114.0 currently looks like this (click to expand):</summary>

```
*   7811c41a6 (HEAD -> master, pulsar/master, deedeeg/master) Merge pull request #956 from pulsar-edit/tree-sitter-ruby-folds
|\  
| *   ab2df0ebf Merge branch 'master' into tree-sitter-ruby-folds
| |\  
| |/  
|/|   
* |   1481d392b Merge pull request #941 from savetheclocktower/tree-sitter-march
|\ \  
| * | 6fe8e5377 (clock/tree-sitter-march) Address feedback
| * | a294c88a4 [language-c] C/C++ highlighting fixes…
| * | 175174e05 [language-javascript] Remove stale TODO comment
| * | 86cb072c5 [symbols-view] Ensure query field contents are initially selected…
| * | e03010582 [language-ruby] Enhancements for percent-array notation in Ruby
| * | 78deb7914 [language-c] Fix issue where the wrong node gets injected into…
| * | 95ca84a58 [language-shellscript] Attempt to bump `tree-sitter-bash` once again
| * | 83a0e127f Update `web-tree-sitter` to custom version of 0.20.9
| * | 579cc2605 [grammar-selector] Show a badge for all kinds of grammars…
| * | e8d4e0b06 [grammar-selector] Simplify fallback options…
| * | df6349af8 Update workspace spec…
| * | b9258b588 [grammar-selector] Overhaul grammar display:
| * | 6c54813c2 Add spec for scope-specific `core.useLegacyTreeSitter` setting
| * | fd37c4dcb Fix issue where we fail to consider legacy Tree-sitter grammars…
| * | ab6f08101 Make divided folds end at the end of the preceding line much more often
| * | 89d410bae Small fixes
| * | 8b0f62b7a Prefer synchronous indentation by default in modern Tree-sitter…
| * | afe6e1e7b Be more aggressive in determining suggested indent positions…
| * | 2827e6a4c [language-typescript] Add `cts(x)`/`mts(x)` to the file extensions lists
| * | 0cea2667a [language-typescript] Highlighting fixes…
| * | 0df4e7528 Simplify the test case and add an explanation
* | |   bc6888ccd Merge pull request #960 from pulsar-edit/cirrus-update-Rolling-token-again
|\ \ \  
| * | | 5455b7d2b (pulsar/cirrus-update-Rolling-token-again, cirrus-update-Rolling-token-again) cirrus: Try to update Rolling upload token again
* | | |   4940e206d Merge pull request #961 from pulsar-edit/cirrus-macOS-fixes
|\ \ \ \  
| |/ / /  
|/| | |   
| * | | 01bf81772 (pulsar/cirrus-macOS-fixes, cirrus-macOS-fixes) cirrus: Various fixes for macOS Cirrus CI
|/ / /  
* | |   3411fb731 Merge pull request #944 from schadomi7/fuzzy-finder-teletype-fix-old-nodejs
|\ \ \  
| * | | 59bdc8d35 Fix fs.lstatSync throws Exception if no file or dir
| |/ /  
| | * c2b501244 (pulsar/tree-sitter-ruby-folds) CHANGELOG update
| | * 0e8a54fda Symbol and string arrays folds for Ruby
| | * 73e9543eb Fixed folds for Ruby
| |/  
|/|   
* |   7d2d876cf Merge pull request #936 from pulsar-edit/CI-update-Cirrus-token
|\ \  
| * | b2b2ed9b2 (pulsar/CI-update-Cirrus-token, CI-update-Cirrus-token) CI: Update Rolling upload token for Cirrus CI
| |/  
* |   5c54aed58 Merge pull request #937 from pulsar-edit/Cirrus-gem-dependencies-fix
|\ \  
| |/  
|/|   
| * cc4e19352 (pulsar/Cirrus-gem-dependencies-fix, Cirrus-gem-dependencies-fix) cirrus: Pin dotenv to semver ~> 2.8, not exact 2.8.1
| * ac73b991b (tag: 1.114.0-Cirrus-hotfix) cirrus: Install older dotenv gem version 2.8.1
* |   4c6d9071c (icecream/master) Merge pull request #929 from pulsar-edit/1.114.0-release
|\ \  
| * | 5bfa0fbca Add back `-dev`
| |/  
| * 62e5ba2f5 (tag: v1.114.0, pulsar/1.114.0-release) Update version
|/  
*   e2a120950 Merge pull request #927 from pulsar-edit/1.114.0-changelog
```

</details>

That includes the following PR's:

- https://github.com/pulsar-edit/pulsar/pull/937
- https://github.com/pulsar-edit/pulsar/pull/944
- https://github.com/pulsar-edit/pulsar/pull/961
- https://github.com/pulsar-edit/pulsar/pull/960
- https://github.com/pulsar-edit/pulsar/pull/941
- https://github.com/pulsar-edit/pulsar/pull/956

**Comment by DeeDeeG** [comment]
Blurb, based predominantly on the draft provided by @savetheclocktower:

```md
## Better Late than Never, Pulsar 1.115.0 is here!

A week later than you’re accustomed to — but worth the wait! Pulsar 1.115.0 is available now!

Last month’s 1.114.0 release was full of fixes related to the recent migration to modern Tree-sitter. This month’s release is much smaller, but still dominated by Tree-sitter fixes affecting syntax highlighting, code folding, and indentation.

The most visible fixes are related to your ability to customize the grammar that Pulsar uses on a per-language basis. This is an approach we’ve encouraged for users that want or need to revert to an older grammar for a specific language — better to do so on a targeted basis than globally. If you can edit your config file, you can do per-language customization.

For instance, now it’s even easier than before to say “use legacy Tree-sitter, but only for Python”:

\```coffeescript
".python.source":
  core:
    useLegacyTreeSitter: true
\```

Or “use modern Tree-sitter for JavaScript, but TextMate-style grammars everywhere else”:

\```coffeescript
"*":
  core:
    useTreeSitterParsers: false
".source.javascript":
  core:
    useTreeSitterParsers: true
\```

Better yet, now the `grammar-selector` package will be attuned to these choices. When you manually reassign a buffer to use a different grammar, it will offer you only the “correct” grammar for each language based on what you’ve opted into.

We’ve also delivered our customary incremental improvements in language support, and one change that affects nearly all languages: indentation hinting will be more accurate in transactions with multiple buffer changes. The most common example of a multi-edit transaction is when the user places more than one cursor and starts typing.

We’ve made improvements to our `language-ruby` bundle, primarily with code folding and indentation hinting. TypeScript and C/C++ also got some small enhancements, and the `language-shellscript` bundle got a parser update.

And lastly, on another note, we have a few maintenance and upkeep PR's to keep our Cirrus CI active and working, to ensure you can keep using and enjoying the latest builds Pulsar has to offer.

Until next time, happy coding, and see you amongst the stars!

\- The Pulsar team

```

**Comment by Daeraxa** [comment]
BUY NITRO:
https://discord.com/channels/992103415163396136/992231561724436591/1220946673791143988
BUY SHARES: https://www.reddit.com/r/pulsaredit/comments/1blj60c/better_late_than_never_pulsar_11150_is_here/?
BUY BANANAS: https://fosstodon.org/@pulsaredit
BUY INTO IT (pls): https://lemmy.ml/post/13532552

**Comment by DeeDeeG** [comment]
I got some error message when trying to publish the Chocolatey package:

> Attempting to push pulsar.1.115.0.nupkg to https://push.chocolatey.org
> An error has occurred. It's possible the package version already exists on the repository or a nuspec element is invalid. See error below...
> Response status code does not indicate success: 409 (Conflict).

At least there's no "pending release" stuck on the Chocolatey.org site side of things, at least that I can see: https://community.chocolatey.org/packages/pulsar#versionhistory

I (or someone with perms to do so) can try tomorrow.

**Comment by confused-Techie** [comment]
Looks like Chocolatey did successfully publish. Thanks everyone for getting this release out, I'll go ahead and close this issue
